<a href="https://colab.research.google.com/github/somiahassan/somiahassan/blob/main/data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lec1

In [ ]:
letters = []
letters.append('c')
letters.append('a')
letters.append('t')
letters.append('g')
print(letters)
last_item = letters.pop()
print(last_item )
print(letters)
last_item = letters.pop()
print(last_item )
print(letters)


['c', 'a', 't', 'g']
g
['c', 'a', 't']
t
['c', 'a']


In [ ]:
fruits = []
fruits.append('banana')
fruits.append('graps')
fruits.append('mango')
fruits.append('orange')

first_item = fruits.pop(0)
print(first_item )

first_item  = fruits.pop(0)
print(first_item  )
print(fruits)

banana
graps
['mango', 'orange']


In [ ]:
from collections import deque
numbers =deque()
numbers.append(99)
numbers.append(15)
numbers.append(82)
numbers.append(50)
numbers.append(47)
print(numbers)
last_item = numbers.pop()
print(last_item)
print(numbers)


deque([99, 15, 82, 50, 47])
47
deque([99, 15, 82, 50])


In [ ]:
from collections import deque
numbers =deque()
numbers.append(99)
numbers.append(15)
numbers.append(82)
numbers.append(50)
numbers.append(47)
print(numbers)
first_item = numbers.popleft()
print(first_item)
print(numbers)

deque([99, 15, 82, 50, 47])
99
deque([15, 82, 50, 47])


# lec2

In [ ]:
file1= open("angil.txt", "w")
L = "this is Delhi \n this is paris \n this is london \n"
file1.write(L)
file1.close()
file1 = open("angil.txt","a")
file1.write("today \n")
file1.close()
file1 = open("angil.txt","r")
print("output of readlines after appending")
print(file1.readlines())
print()
file1.close()
file1 = open("angil.txt","a")
file1.write("tomorrow \n")
file1.close()
file1= open("angil.txt","r")
print("output of readlines after writing")
print(file1.readlines())
print()
file1.close()

output of readlines after appending
['this is Delhi \n', ' this is paris \n', ' this is london \n', 'today \n']

output of readlines after writing
['this is Delhi \n', ' this is paris \n', ' this is london \n', 'today \n', 'tomorrow \n']



In [ ]:
import pickle
omkar={'key':'omkar', 'name':'omkar pathak', 'age':21, 'pay':40000}
jagdish={'key':'jadgish', 'name':'jadish pathak', 'age':50,'pay':50000}
db={}
db['omkar']=omkar
db['jagdish']=jagdish
b = pickle.dumps(db)
myEntry=pickle.loads(b)
print(myEntry)


{'omkar': {'key': 'omkar', 'name': 'omkar pathak', 'age': 21, 'pay': 40000}, 'jagdish': {'key': 'jadgish', 'name': 'jadish pathak', 'age': 50, 'pay': 50000}}


In [ ]:
import numpy as np
vector = np.array([1,2,3])
matrix = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("vector:\n", vector)
print("matrix:\n",matrix)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

print(np.zeros((3,6)))
np.zeros(5, dtype=int)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([0, 0, 0, 0, 0])

In [ ]:
b=(np.ones(5, dtype=int))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.data)
a=np.ones((3,5))
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.data)

[1 1 1 1 1]
1
(5,)
5
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
(3, 5)
15


In [ ]:
print(np.full(10,5))
np.full((4,7),4)

[5 5 5 5 5 5 5 5 5 5]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
a=np.arange(10)
c=np.arange(1,10)
b=np.arange(100,12,-1)
#c=np.arange()
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13]
[1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.random.random(10))
np.random.random((3,4))

[0.7856305  0.95453601 0.34607419 0.84348969 0.48639406 0.47898443
 0.95907429 0.50026956 0.43321533 0.60754047]


array([[0.78466805, 0.08115737, 0.9437124 , 0.25926748],
       [0.71935629, 0.22689563, 0.15492281, 0.54008749],
       [0.93579711, 0.59201864, 0.28961009, 0.63233675]])

In [ ]:
print(np.random.normal(2,3,4))
np.random.normal()
#np.random.normal(0,1,(3,4))
print(np.random.randint(0,100,(3,4)))
print(np.random.rand(3,4))

[-4.30042086  4.0170377  -0.97671379  1.77566959]
[[ 8 38 22 59]
 [20 76 92 67]
 [ 8 40 27 67]]
[[0.29837354 0.72241348 0.41865201 0.03944794]
 [0.02441189 0.45367535 0.01587957 0.14921601]
 [0.42312481 0.78439405 0.77367837 0.28584532]]


In [ ]:
print(np.linspace(0,5,10))
print(np.linspace(4,2,5))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[4.  3.5 3.  2.5 2. ]


In [ ]:
np.linspace(0,5,7,endpoint=False)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429])

In [ ]:
import numpy as np
print(np.eye(4,4,1))
print(np.eye(4,4,-1))
print(np.eye(4,4))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x1=[5,0,3,3,7,9]
print(x1[-6])
print(x1[0:3])
print(x1[0:5:2])
x1[4]=10
x1[1]=4
print(type(x1))
x1

5
[5, 0, 3]
[5, 3, 7]
<class 'list'>


[5, 4, 3, 3, 10, 9]

In [ ]:
x2=np.array([[1,2,3],[4,5,6]])
print(type(x2))
x2.shape
print(x2[0][0])
print(x2[1][0])
print(x2[1][1])
print(x2[0][2])
print(x2[0][1])
print(x2[1][2])
x2[1][1]=7
x2
x2[0][0]=10
x2
x2[0][1]=20
x2

<class 'numpy.ndarray'>
1
4
5
3
2
6


array([[10, 20,  3],
       [ 4,  7,  6]])

# lec3

-broadcasting: (بعمل عمليات جمع وطرح وضرب وقسمة علي مصفوفات مختلفة في حجم)

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,5,5])
print(a+b)
print(a+5)
print(a*5)
#jتكرار لخمسة مع تلات عناصر
m=np.ones((3,3))#different one dimension can apply broadcast
print (m)
print(m+a)
# a=np.array([1,2,3])#different two dimension no broadcast
# print(a)
# b=np.array([[1,2],[3,4]])
# print(b)

# print(a+b)

[6 7 8]
[6 7 8]
[ 5 10 15]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
a=np.arange(3)
b=np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a+b)
print(a*b)


[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]


-comparsion operator: عمليات مقارنة اكبر واصغر وتساوي ولا يساوي

In [ ]:
x = np.array([1,2,3,4,5])
print(x<3)
print(x>3)
print(x!=3)#not equal
print(x*2 == x**2)#single star multiplication(ضرب),two star exponentional(اس)

[ True  True False False False]
[False False False  True  True]
[ True  True False  True  True]
[False  True False False False]


# lec4

algorithms tree

In [ ]:
! pip install bigtree

In [ ]:
from bigtree import Node,print_tree,tree_to_dict,tree_to_dot
a = Node("a", age=90)
b= Node("b", age=65, parent=a)
c= Node("c", age=60, parent=a)
d=Node("d", age=20, parent=b)
e=Node("e", age=20, parent=b)
print(a.children)
print(b.children)
print(a.depth)
print(b.depth)
print(a.max_depth)
a.show(attr_list=["age"])
print(print_tree(a,attr_list=["age"], style="ascii"))
print(tree_to_dict(a, all_attrs=True))
print(tree_to_dict(a,attr_dict={"age":"AGE"} ))
graph=tree_to_dot(a)
print(graph.write_png("tree.png"))
graph.write_dot("tree.dot")
graph.to_string()

(Node(/a/b, age=65), Node(/a/c, age=60))
(Node(/a/b/d, age=20), Node(/a/b/e, age=20))
1
2
3
a [age=90]
├── b [age=65]
│   ├── d [age=20]
│   └── e [age=20]
└── c [age=60]
a [age=90]
|-- b [age=65]
|   |-- d [age=20]
|   +-- e [age=20]
+-- c [age=60]
None
{'/a': {'name': 'a', 'age': 90}, '/a/b': {'name': 'b', 'age': 65}, '/a/b/d': {'name': 'd', 'age': 20}, '/a/b/e': {'name': 'e', 'age': 20}, '/a/c': {'name': 'c', 'age': 60}}
{'/a': {'name': 'a', 'AGE': 90}, '/a/b': {'name': 'b', 'AGE': 65}, '/a/b/d': {'name': 'd', 'AGE': 20}, '/a/b/e': {'name': 'e', 'AGE': 20}, '/a/c': {'name': 'c', 'AGE': 60}}
None


'strict digraph G {\nrankdir=TB;\na0 [label=a];\nb0 [label=b];\na0 -> b0;\nd0 [label=d];\nb0 -> d0;\ne0 [label=e];\nb0 -> e0;\nc0 [label=c];\na0 -> c0;\n}\n'

In [ ]:
from bigtree import Node
a = Node("a", age=90)
b= Node("b", age=65, parent=a)
c= Node("c", age=60, parent=a)
d=Node("d", age=20, parent=b)
g=Node("g", age=20, parent=b)
h=Node("h",age=35,parent=c)
f=Node("f",age=20,parent=d)
a.show(attr_list=["age"])

a [age=90]
├── b [age=65]
│   ├── d [age=20]
│   │   └── f [age=20]
│   └── g [age=20]
└── c [age=60]
    └── h [age=35]


In [ ]:
from bigtree import list_to_tree
path_list=["a/b/d","a/b/e","a/c"]
root=list_to_tree(path_list)
root.show()

a
├── b
│   ├── d
│   └── e
└── c


In [ ]:
from bigtree import list_to_tree
path_list=["a/b/d/f","a/b/g","a/c/h"]
root=list_to_tree(path_list)
root.show()

a
├── b
│   ├── d
│   │   └── f
│   └── g
└── c
    └── h


In [ ]:
from bigtree import dict_to_tree
path_dict={
    "a":{"age":90},
    "a/b":{"age":65},
    "a/c":{"age":60},
    "a/b/d":{"age":40},
    "a/b/e":{"age":35},
}
root=dict_to_tree(path_dict)
root.show(attr_list=["age"])

a [age=90]
├── b [age=65]
│   ├── d [age=40]
│   └── e [age=35]
└── c [age=60]


In [ ]:
from bigtree import dict_to_tree
path_dict={
    "a":{"age":90},
    "a/b":{"age":65},
    "a/c":{"age":60},
    "a/b/d":{"age":40},
    "a/b/9":{"age":40},
    "a/c/h":{"age":30},
    "a/b/d/f":{"age":20},
}
root=dict_to_tree(path_dict)
root.show(attr_list=["age"])

a [age=90]
├── b [age=65]
│   ├── d [age=40]
│   │   └── f [age=20]
│   └── 9 [age=40]
└── c [age=60]
    └── h [age=30]


In [ ]:
import pandas as pd
from bigtree import dataframe_to_tree
path_data=pd.DataFrame([
    ["a",90],
    ["a/b",65],
    ["a/c",60],
    ["a/b/d",40],
    ["a/b/e",35],
],columns=["path","age"])
root=dataframe_to_tree(path_data)
root.show(attr_list=["age"])

a [age=90]
├── b [age=65]
│   ├── d [age=40]
│   └── e [age=35]
└── c [age=60]


In [ ]:
import pandas as pd
from bigtree import dataframe_to_tree
path_data=pd.DataFrame([
    ["a",90],
    ["a/b",65],
    ["a/c",60],
    ["a/b/d",40],
    ["a/b/g",35],
    ["a/c/h",30],
    ["a/b/d/f",20]
],columns=["path","age"])
root=dataframe_to_tree(path_data)
root.show(attr_list=["age"])

a [age=90]
├── b [age=65]
│   ├── d [age=40]
│   │   └── f [age=20]
│   └── g [age=35]
└── c [age=60]
    └── h [age=30]


# Lec5-search and modification tree

In [ ]:
! pip install bigtree

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 2.1 MB/s eta 0:00:00


search : ابحث عن نقطة جوة شجرة او اكتر من نقطة بمعلومية attribute

In [ ]:
from bigtree import Node, find, findall
root=Node("a", age=90)
b=Node("b", age=65, parent=root)
c=Node("c", age=60, parent=root)
d=Node("d", age=40, parent=b)
root.show(attr_list=["age"])
print(find(root, lambda node: node.age==40))
print(findall(root, lambda node: node.age>=60))

a [age=90]
├── b [age=65]
│   └── d [age=40]
└── c [age=60]
Node(/a/c, age=60)
(Node(/a, age=90), Node(/a/b, age=65), Node(/a/c, age=60))


modification: تعديل جوة tree بمعلومية attribute تنقل النقطة من مشار لاخر

In [ ]:
from bigtree import Node, shift_nodes
a=Node("List")
groceries=Node("Groceries", parent=a)
urgent=Node("Urgent", parent=a)
groceries_milk=Node("Milk", parent=urgent)
print(a.show())
shift_nodes(a,from_paths=["List/Urgent/Milk"],to_paths=["List/Groceries/Milk"])
print(a.show())


List
├── Groceries
└── Urgent
    └── Milk
None
List
├── Groceries
│   └── Milk
└── Urgent
None


# lec6:tree

In [ ]:
from bigtree import Node,print_tree,tree_to_dict,tree_to_dot
a = Node("a", age=90)
b= Node("b", age=65, parent=a)
c= Node("c", age=60, parent=a)
d=Node("d", age=20, parent=b)
e=Node("e", age=20, parent=b)
print(a.children)
print(b.children)
print(a.depth)
print(b.depth)
print(a.max_depth)
print(a.show(attr_list=["age"]))
print(print_tree(a,attr_list=["age"], style="ascii"))
print(tree_to_dict(a, all_attrs=True))
print(tree_to_dict(a,attr_dict={"age":"AGE"} ))
graph=tree_to_dot(a)
print(graph.write_png("tree.png"))
print(graph.write_dot("tree.dot"))
print(graph.to_string())

(Node(/a/b, age=65), Node(/a/c, age=60))
(Node(/a/b/d, age=20), Node(/a/b/e, age=20))
1
2
3
a [age=90]
├── b [age=65]
│   ├── d [age=20]
│   └── e [age=20]
└── c [age=60]
None
a [age=90]
|-- b [age=65]
|   |-- d [age=20]
|   +-- e [age=20]
+-- c [age=60]
None
{'/a': {'name': 'a', 'age': 90}, '/a/b': {'name': 'b', 'age': 65}, '/a/b/d': {'name': 'd', 'age': 20}, '/a/b/e': {'name': 'e', 'age': 20}, '/a/c': {'name': 'c', 'age': 60}}
{'/a': {'name': 'a', 'AGE': 90}, '/a/b': {'name': 'b', 'AGE': 65}, '/a/b/d': {'name': 'd', 'AGE': 20}, '/a/b/e': {'name': 'e', 'AGE': 20}, '/a/c': {'name': 'c', 'AGE': 60}}
None
None
strict digraph G {
rankdir=TB;
a0 [label=a];
b0 [label=b];
a0 -> b0;
d0 [label=d];
b0 -> d0;
e0 [label=e];
b0 -> e0;
c0 [label=c];
a0 -> c0;
}



1-to_dolist

In [ ]:
from bigtree import AppToDo
app=AppToDo("family name")
app.add_item(item_name="homework 1", list_name="school")
app.add_item(item_name=["milk","brid"], list_name="groceries",description="urgent")
app.add_item(item_name="cook")
app.show()
app.save("tree.json")
app2=AppToDo.load("tree.json")

family name
├── school
│   └── homework 1
├── groceries
│   ├── milk [description=urgent]
│   └── brid [description=urgent]
└── General
    └── cook


2-extend tree_trie

In [ ]:
from bigtree import list_to_tree, find_path
bag_words=["ant","and","angry","buoy","buoyant"]
print(type(bag_words))
list_of_path=["/".join(["^"] + list(x) + ["$"]) for x in bag_words]
print(list_of_path)
trie=list_to_tree(list_of_path)
print(find_path(trie,"/".join(list("^and$"))))
print(find_path(trie,"/".join(list("^boy$"))))

<class 'list'>
['^/a/n/t/$', '^/a/n/d/$', '^/a/n/g/r/y/$', '^/b/u/o/y/$', '^/b/u/o/y/a/n/t/$']
Node(/^/a/n/d/$, )
None


3-directed cycle graph

In [ ]:
from bigtree import DAGNode, dag_to_dot
a=DAGNode("Ingest data from source A")
b=DAGNode("Ingest data from source b")
c=DAGNode("clean data", parents=[a,b])
d=DAGNode("feature engineering", parents=[c])
graph=dag_to_dot(a, node_colour="red")
graph.write_png("d1.png")

# lec7:sorting algorithms

1-buble algorithm:

In [ ]:
def bubble_sort(arr):
  n=len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
arr=[20,5,3,8]
bubble_sort(arr)
print("ordered array:")
for i in range(len(arr)):
  print(arr[i])


ordered array:
3
5
8
20


In [ ]:
def bubble_sort(arr):
  n=len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]<arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
arr=[20,5,3,8]
bubble_sort(arr)
print("ordered array:")
for i in range(len(arr)):
  print(arr[i])

ordered array:
20
8
5
3


2- selection sort

In [ ]:
def selection_sort(arr,size):
  for s in range (size):
    min_index=s
    for i in range(s+1,size):
      if arr[i]<arr[min_index]:
        min_index=i
        arr[s],arr[min_index]=arr[min_index],arr[s]
arr=[30,6,4,2]
size=len(arr)
selection_sort(arr,size)
print(arr)
for i in range(len(arr)):
  print(arr[i])

[2, 4, 6, 30]
2
4
6
30


# searching algorithms

1-linear search

In [ ]:
def selection_sort(arr,size):
  for s in range (size):
    max_index=s
    for i in range(s+1,size):
      if arr[i]>arr[max_index]:
        max_index=i
        arr[s],arr[max_index]=arr[max_index],arr[s]
arr=[30,6,4,2]
size=len(arr)
selection_sort(arr,size)
print(arr)
for i in range(len(arr)):
  print(arr[i])

[30, 6, 4, 2]
30
6
4
2


3- insertion sort

In [ ]:
def insertion_sort(list1):
  #outer loop of traverse list
  for i in range(1,len(list1)):
    a=list1[i]
    #sorted part one greater than other
    j=i-1
    while j>=0 and a<list1[j]:
      list1[j+1]=list1[j]
      j -=1
    list1[j+1]=a
  return list1
list1=[7,2,1,6]
print("the unsorted list is:",list1)
print("the new sorted list is",insertion_sort(list1))


the unsorted list is: [7, 2, 1, 6]
the new sorted list is [1, 2, 6, 7]


# Searching algorithms

1-linear search

In [ ]:
def linear_search(target,arr):
  for i in range(0,len(arr)):
    if arr[i] == target:
      return i

  return -1
arr=[1,4,5,10]
target=10
len(arr)
result=linear_search(target,arr)
if result !=-1:
  print("element is in list and index:",result)
else:
  print("element not in list")


element is in list and index: 3


In [ ]:
def linear_search(target,arr):
  for i in range(0,len(arr)):
    if arr[i] == target:
      return i

  return -1
arr=[1,4,5,10]
target=input("enter your element search")
print(type(target))
len(arr)
result=linear_search(target,arr)
if result !=-1:
  print("element is in list and index:",result)
else:
  print("element not in list")

enter your element search40
<class 'str'>
element not in list


2-binary classification

In [ ]:
def binary_search(arr,target,low,high):
  if low<= high:
    mid = (low+high)//2

    if arr[mid]== target:
      return mid
    elif arr[mid]<target:
      return binary_search(arr,target,mid+1,high)
    else:
      return binary_search(arr,target,low,mid-1)
  else:
    return -1
arr=[5,2,10,3]
target=3
result=binary_search(sorted(arr),target,0,len(arr)-1)
print(result)


1


In [ ]:
def binary_search(arr,target,low,high):
  if low<= high:
    mid = (low+high)//2

    if arr[mid]== target:
      return mid
    elif arr[mid]<target:
      return binary_search(arr,target,mid+1,high)
    else:
      return binary_search(arr,target,low,mid-1)
  else:
    return -1
arr=[5,2,10,3]
target=10
result=binary_search(sorted(arr),target,0,len(arr)-1)
print(result)

3


3-interpolation algorithm